#

pluginName = webApplications Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_WebApplication_type = Web Application
_UI_Page_type = Page
_UI_Database_type = Database
_UI_User_type = User
_UI_Customer_type = Customer
_UI_Admin_type = Admin
_UI_Product_type = Product
_UI_Order_type = Order
_UI_Shoppingcart_type = Shoppingcart
_UI_WelcomePage_type = Welcome Page
_UI_PrroductPage_type = Prroduct Page
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_WebApplication_name_feature = Name
_UI_WebApplication_page_feature = Page
_UI_WebApplication_database_feature = Database
_UI_Page_pageID_feature = Page ID
_UI_Page_name_feature = Name
_UI_Database_name_feature = Name
_UI_Database_type_feature = Type
_UI_Database_connURL_feature = Conn URL
_UI_Database_user_feature = User
_UI_Database_product_feature = Product
_UI_Database_order_feature = Order
_UI_User_userID_feature = User ID
_UI_User_userName_feature = User Name
_UI_User_isAdmin_feature = Is Admin
_UI_Customer_eMail_feature = EMail
_UI_Customer_adress_feature = Adress
_UI_Product_productID_feature = Product ID
_UI_Product_quantity_feature = Quantity
_UI_Product_name_feature = Name
_UI_Product_category_feature = Category
_UI_Product_price_feature = Price
_UI_Order_orderID_feature = Order ID
_UI_Order_product_feature = Product
_UI_Shoppingcart_product_feature = Product
_UI_Unknown_feature = Unspecified

_UI_ProductPage_type = Product Page
_UI_ProductPage_product_feature = Product
_UI_CheckoutPage_type = Checkout Page
_UI_Page_description_feature = Description
_UI_Customer_shoppingcart_feature = Shoppingcart
_UI_Customer_order_feature = Order
_UI_Product_description_feature = Description
_UI_Order_date_feature = Date
_UI_Order_status_feature = Status
_UI_Order_totalPrice_feature = Total Price
_UI_Shoppingcart_cartID_feature = Cart ID
_UI_Shoppingcart_totalPrice_feature = Total Price
